name: Hearts
main: pro.noty.heart.Hearts
version: 1.2.0
api-version: 1.21
author: Noty
description: Show floating hearts above players and mobs with Vault balance.
softdepend: [Vault, Floodgate, Geyser]
